// <auto-generated />
using System;
using Lotus.DeNova;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lotus.DeNova.Migrations
{
    [DbContext(typeof(DeNovaDbContext))]
    [Migration("20230825164628_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lotus.Account.CAvatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("FullImage")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("SmallImage")
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.ToTable("Avatar", "adm");
                });

            modelBuilder.Entity("Lotus.Account.CDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CodeId")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Family")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsMobileDevice")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Device", "adm");
                });

            modelBuilder.Entity("Lotus.Account.CFieldActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("FieldActivity", "adm");
                });

            modelBuilder.Entity("Lotus.Account.CGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Group", "adm");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Хранители",
                            ShortName = "Хранители"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Север",
                            ShortName = "Север"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Юг",
                            ShortName = "Юг"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Восток",
                            ShortName = "Восток"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Запад",
                            ShortName = "Запад"
                        });
                });

            modelBuilder.Entity("Lotus.Account.CMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Message", "adm");
                });

            modelBuilder.Entity("Lotus.Account.CNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Importance")
                        .HasColumnType("integer");

                    b.Property<bool>("IsArchive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Sender")
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notification", "adm");
                });

            modelBuilder.Entity("Lotus.Account.CPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DispalyName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Permission", "adm");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DispalyName = "Администрирование системы",
                            SystemName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            DispalyName = "Модератор",
                            SystemName = "editor"
                        },
                        new
                        {
                            Id = 3,
                            DispalyName = "Пользователь",
                            SystemName = "user"
                        });
                });

            modelBuilder.Entity("Lotus.Account.CPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Position", "adm");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Инспектор",
                            ShortName = "Инспектор"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Старший инспектор",
                            ShortName = "Старший инспектор"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ведущий специалист",
                            ShortName = "Ведущий специалист"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Начальник отдела",
                            ShortName = "Начальник отдела"
                        });
                });

            modelBuilder.Entity("Lotus.Account.CRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DispalyName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Role", "adm");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DispalyName = "Администратор",
                            SystemName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            DispalyName = "Редактор",
                            SystemName = "editor"
                        },
                        new
                        {
                            Id = 3,
                            DispalyName = "Пользователь",
                            SystemName = "user"
                        });
                });

            modelBuilder.Entity("Lotus.Account.CRolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission", "adm");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 3,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Lotus.Account.CSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BeginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Browser")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("UserId");

                    b.ToTable("Session", "adm");
                });

            modelBuilder.Entity("Lotus.Account.CUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AvatarId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<int?>("PostId")
                        .HasColumnType("integer");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("RoleSystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.HasIndex("PostId");

                    b.HasIndex("RoleId");

                    b.ToTable("User", "adm");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e3182c8f-87bc-4e27-a27f-b32e3e2b8018"),
                            Email = "dementevds@gmail.com",
                            EmailConfirmed = false,
                            Login = "DanielDem",
                            Name = "Даниил",
                            PasswordHash = "012f28fd2973783520fa3115f886102a09c8a15e",
                            Patronymic = "Сергеевич",
                            RoleId = 1,
                            RoleSystemName = "Нет роли",
                            Surname = "Дементьев"
                        });
                });

            modelBuilder.Entity("Lotus.Account.CUserFieldActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FieldActivityId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FieldActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFieldActivity", "adm");
                });

            modelBuilder.Entity("Lotus.Account.CUserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGroup", "adm");
                });

            modelBuilder.Entity("Lotus.DeNova.AddressElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CadastralNumber")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<string>("Code")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<int>("ElementType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<int?>("StreetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StreetId");

                    b.ToTable("AddressElement", "denova");
                });

            modelBuilder.Entity("Lotus.DeNova.AddressInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AddressId")
                        .HasColumnType("integer");

                    b.Property<Guid>("AddressInfoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BeginPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndPeriod")
                        .HasColumnType("date");

                    b.Property<Guid>("GameContextId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GameSaveId")
                        .HasColumnType("uuid");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("PersonId");

                    b.ToTable("AddressInfo", "denova");
                });

            modelBuilder.Entity("Lotus.DeNova.AddressStreet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("StreetType")
                        .HasColumnType("integer");

                    b.Property<int?>("VillageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VillageId");

                    b.ToTable("AddressStreet", "denova");
                });

            modelBuilder.Entity("Lotus.DeNova.AddressVillage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("OKATO")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("OKTMO")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("VillageSettlementId")
                        .HasColumnType("integer");

                    b.Property<int>("VillageType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VillageSettlementId");

                    b.ToTable("AddressVillage", "denova");
                });

            modelBuilder.Entity("Lotus.DeNova.AddressVillageSettlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VillageSettlementType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AddressVillageSettlement", "denova");
                });

            modelBuilder.Entity("Lotus.DeNova.Astrology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignSettingId")
                        .HasColumnType("integer");

                    b.Property<string>("StoneZodiac")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TreeZodiac")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ZodiacSign")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Astrology", "denova");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampaignSettingId = 1,
                            StoneZodiac = "Алмаз",
                            TreeZodiac = "Лиана",
                            ZodiacSign = "Змееносец"
                        },
                        new
                        {
                            Id = 2,
                            CampaignSettingId = 1,
                            StoneZodiac = "Изумруд",
                            TreeZodiac = "Ива",
                            ZodiacSign = "Кецалькоатль"
                        },
                        new
                        {
                            Id = 3,
                            CampaignSettingId = 1,
                            StoneZodiac = "Топаз",
                            TreeZodiac = "Дуб",
                            ZodiacSign = "Телец"
                        });
                });

            modelBuilder.Entity("Lotus.DeNova.AvatarInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AvatarInfoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BeginPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameContextId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GameSaveId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ImageId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("PersonId");

                    b.ToTable("AvatarInfo", "denova");
                });

            modelBuilder.Entity("Lotus.DeNova.BirthdayInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AddressId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GameContextId")
                        .HasColumnType("uuid");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("PersonId");

                    b.ToTable("BirthdayInfo", "denova");
                });

            modelBuilder.Entity("Lotus.DeNova.CampaignSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("CampaignSetting", "denova");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Сентра",
                            Name = "Sentra"
                        });
                });

            modelBuilder.Entity("Lotus.DeNova.GameContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CampaignSettingId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("GameContext", "denova");
                });

            modelBuilder.Entity("Lotus.DeNova.GameSave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("GameContextId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Modified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("GameSave", "denova");
                });

            modelBuilder.Entity("Lotus.DeNova.IdentityInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BeginPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CodeID")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("EndPeriod")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FatherName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("GameContextId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GameSaveId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdentityInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("IdentityInfo", "denova");
                });

            modelBuilder.Entity("Lotus.DeNova.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignSettingId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("DataImage")
                        .HasColumnType("bytea");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("boolean");

                    b.Property<string>("LoadPath")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SizeInBytes")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Image", "denova");
                });

            modelBuilder.Entity("Lotus.DeNova.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AstrologyId")
                        .HasColumnType("integer");

                    b.Property<int?>("AvatarId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AstrologyId");

                    b.HasIndex("AvatarId");

                    b.HasIndex("RaceId");

                    b.ToTable("Person", "denova");
                });

            modelBuilder.Entity("Lotus.DeNova.PlacementInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameContextId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GameSaveId")
                        .HasColumnType("uuid");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlacementInfoId")
                        .HasColumnType("uuid");

                    b.Property<int>("PositionX")
                        .HasColumnType("integer");

                    b.Property<int>("PositionY")
                        .HasColumnType("integer");

                    b.Property<int>("PositionZ")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PlacementInfo", "denova");
                });

            modelBuilder.Entity("Lotus.DeNova.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignSettingId")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Race", "denova");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampaignSettingId = 1,
                            DisplayName = "Эриец",
                            Name = "Erian"
                        },
                        new
                        {
                            Id = 2,
                            CampaignSettingId = 1,
                            DisplayName = "Завротеанен",
                            Name = "Zavroteanen"
                        },
                        new
                        {
                            Id = 3,
                            CampaignSettingId = 1,
                            DisplayName = "Леохарт",
                            Name = "Leohart"
                        },
                        new
                        {
                            Id = 4,
                            CampaignSettingId = 1,
                            DisplayName = "Триб",
                            Name = "Tribe"
                        },
                        new
                        {
                            Id = 5,
                            CampaignSettingId = 1,
                            DisplayName = "Гнол",
                            Name = "Gnol"
                        },
                        new
                        {
                            Id = 6,
                            CampaignSettingId = 1,
                            DisplayName = "Эль`гоу",
                            Name = "Elgou"
                        },
                        new
                        {
                            Id = 7,
                            CampaignSettingId = 1,
                            DisplayName = "Фергариец",
                            Name = "Fergarian"
                        });
                });

            modelBuilder.Entity("Lotus.Account.CMessage", b =>
                {
                    b.HasOne("Lotus.Account.CUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Lotus.Account.CUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId");

                    b.Navigation("Author");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("Lotus.Account.CRolePermission", b =>
                {
                    b.HasOne("Lotus.Account.CPermission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lotus.Account.CRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lotus.Account.CSession", b =>
                {
                    b.HasOne("Lotus.Account.CDevice", "Device")
                        .WithMany("Sessions")
                        .HasForeignKey("DeviceId");

                    b.HasOne("Lotus.Account.CUser", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId");

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lotus.Account.CUser", b =>
                {
                    b.HasOne("Lotus.Account.CAvatar", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.HasOne("Lotus.Account.CPosition", "Post")
                        .WithMany("Users")
                        .HasForeignKey("PostId");

                    b.HasOne("Lotus.Account.CRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Avatar");

                    b.Navigation("Post");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Lotus.Account.CUserFieldActivity", b =>
                {
                    b.HasOne("Lotus.Account.CFieldActivity", null)
                        .WithMany()
                        .HasForeignKey("FieldActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lotus.Account.CUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lotus.Account.CUserGroup", b =>
                {
                    b.HasOne("Lotus.Account.CGroup", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lotus.Account.CUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lotus.DeNova.AddressElement", b =>
                {
                    b.HasOne("Lotus.DeNova.AddressStreet", "Street")
                        .WithMany("Elements")
                        .HasForeignKey("StreetId");

                    b.Navigation("Street");
                });

            modelBuilder.Entity("Lotus.DeNova.AddressInfo", b =>
                {
                    b.HasOne("Lotus.DeNova.AddressElement", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Lotus.DeNova.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Lotus.DeNova.AddressStreet", b =>
                {
                    b.HasOne("Lotus.DeNova.AddressVillage", "Village")
                        .WithMany("Streets")
                        .HasForeignKey("VillageId");

                    b.Navigation("Village");
                });

            modelBuilder.Entity("Lotus.DeNova.AddressVillage", b =>
                {
                    b.HasOne("Lotus.DeNova.AddressVillageSettlement", "VillageSettlement")
                        .WithMany("Villages")
                        .HasForeignKey("VillageSettlementId");

                    b.Navigation("VillageSettlement");
                });

            modelBuilder.Entity("Lotus.DeNova.AvatarInfo", b =>
                {
                    b.HasOne("Lotus.DeNova.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("Lotus.DeNova.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Lotus.DeNova.BirthdayInfo", b =>
                {
                    b.HasOne("Lotus.DeNova.AddressElement", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Lotus.DeNova.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Lotus.DeNova.IdentityInfo", b =>
                {
                    b.HasOne("Lotus.DeNova.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Lotus.DeNova.Person", b =>
                {
                    b.HasOne("Lotus.DeNova.Astrology", "Astrology")
                        .WithMany()
                        .HasForeignKey("AstrologyId");

                    b.HasOne("Lotus.DeNova.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.HasOne("Lotus.DeNova.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Astrology");

                    b.Navigation("Avatar");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Lotus.DeNova.PlacementInfo", b =>
                {
                    b.HasOne("Lotus.DeNova.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Lotus.Account.CDevice", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Lotus.Account.CPosition", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Lotus.Account.CRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Lotus.Account.CUser", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Lotus.DeNova.AddressStreet", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("Lotus.DeNova.AddressVillage", b =>
                {
                    b.Navigation("Streets");
                });

            modelBuilder.Entity("Lotus.DeNova.AddressVillageSettlement", b =>
                {
                    b.Navigation("Villages");
                });
#pragma warning restore 612, 618
        }
    }
}
